cacheFolder: .yarn/cache

enableGlobalCache: false

nodeLinker: node-modules

npmPublishRegistry: "https://registry.npmjs.org"

npmScopes:
  quatrain:
    npmPublishRegistry: "https://registry.npmjs.org"

packageExtensions:
  "jest-serial-runner@*":
    peerDependenciesMeta:
      "jest-runner":
        optional: true

logFilters:
  - code: YN0002
    level: discard
  - code: YN0086
    level: discard
