# SonarQube / SonarCloud Project Metadata
sonar.projectKey=Quatrain_CoreUX
sonar.organization=quatrain-technologies

# Sources and Tests Configuration
sonar.sources=packages
sonar.tests=packages
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.test.js,**/*.test.jsx
sonar.exclusions=**/node_modules/**,**/dist/**/*.js,**/dist/**/*.js.map,**/build/**,**/coverage/**

# Javascript & Typescript Coverage Settings
sonar.javascript.lcov.reportPaths=coverage/lcov.info
